print("            #############")
print("            #           #")
print("            #   #    #  #")
print("            #     O     #")
print("            #   _____   #")
print("            #           #")
print("            #############")
print("              #       #       ")
print("              #       #       ")
print("              #       #       ")
print("              #       #       ")