print("            ##########")
print("            #  -  -  #")
print("            #  ----  #")
print("            ##########")
print()
print("Please enter a character for the eye")
o = input()
print("Beep's expression is now as follows:")
print()
print("            ##########")
print("            #  o  o  #")
print("            #  ----  #")
print("            ##########")
